### ISSUE TITLE
Treatments: Why does Diagnosis code use VENOM instead of ICAR

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#30]
This is more of a question, we were wondering if the ICAR codes were considered?

https://www.icar.org/index.php/publications-technical-materials/amendments-recording-guidelines/diseases-codes-for-cows/

**Comment by cookeac** [comment]
They were considered. We looked at a number of actual implementations for sharing health data, and the only coding scheme actually in use in those implementations was VeNom. However, it was a small sample!
We could:
1. Add an ICAR code as another option; or
2. Define a DiagnosisCodeType (derived from the genetic icarIdentifierType), so that we could use the scheme + ID method to support different diagnosis coding systems.
Something to discuss at the meeting.

**Comment by cookeac** [comment]
At the meeting the preference seemed to be to support scheme and value based on icarIdentifierType.
For instance { "scheme": "org.venom", "id": "123456" } or { "scheme": "org.icar", "id": "234567" }.

**Comment by anitanagaraj** [comment]
Updated spreadsheet

**Comment by AndyDe-Aldent** [comment]
Need to update pull request to follow updated spreedsheet

**Comment by AndyDe-Aldent** [comment]
Updated the existing iscDiagnosisType.json and added the new iscDiagnosisIdentifierType.json file in the currently open pull request.

**Comment by cookeac** [comment]
Merged PR
