### ISSUE TITLE
Movement: Arrival: Duplicate animal... kind of

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#40]
Animal is already on icarEventCoreResource.This feels like a double up. How would this double up addresed?

**Comment by cookeac** [comment]
This is by design for Arrivals and Registrations.
* The Animal reference in icarEventCoreResource is the ID of the observed animal.
* If an animal is being added to a system by POSTing an induction event, there needs to be a mechanism to populate its life data. The animalDetails object achieves this.
