### ISSUE TITLE
Weigh - Measurement object

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#9]
Is it worth using types to encapsulate the values in an observation?

The example in score would be a weight wrapping value, units and resolution.

**Comment by anitanagaraj** [comment]
It is good idea if we think we will use these measurement types frequently.

**Comment by cookeac** [comment]
We are leaning towards creating the following to support various measurements (See also issue #31):
  iscMeasurementType - defines value, resolution
  iscMassMeasurementType - adds units for mass
  iscVolumeMeasurementType - defines units for volume
  iscDistanceMeasurementType - defines units for distance or length
This allows the enumerations of units to be specific, which will aid developers in developing appropriate mappings from their internal data to UN/CEFACT units.

Thus in a weight event...
  "weight": { "$ref": "iscMassMeasurementType" }

We discussed doing the same with Dose (for medicines), but it has a specific set of units relevant to medicines, drenches, and related treatments, rather than a general mass unit. Resolution is also less useful for Dose.

**Comment by cookeac** [comment]
Defined iscMeasurementType.json and iscMassMeasurementType.json. Changed iscWeightEventResource.json to use these. See PR #67
